// Code generated by protoc-gen-go. DO NOT EDIT.
// source: p.proto

package catalog

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RespType int32

const (
	RespType_NONE    RespType = 0
	RespType_ASCEND  RespType = 1
	RespType_DESCEND RespType = 2
)

var RespType_name = map[int32]string{
	0: "NONE",
	1: "ASCEND",
	2: "DESCEND",
}

var RespType_value = map[string]int32{
	"NONE":    0,
	"ASCEND":  1,
	"DESCEND": 2,
}

func (x RespType) String() string {
	return proto.EnumName(RespType_name, int32(x))
}

func (RespType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_abe44bf90c1c2369, []int{0}
}

type BaseInfo struct {
	BaseInfoTypeId       int32    `protobuf:"varint,1,opt,name=baseInfoTypeId,proto3" json:"baseInfoTypeId,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Column               string   `protobuf:"bytes,3,opt,name=column,proto3" json:"column,omitempty"`
	SortNo               int32    `protobuf:"varint,4,opt,name=sortNo,proto3" json:"sortNo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseInfo) Reset()         { *m = BaseInfo{} }
func (m *BaseInfo) String() string { return proto.CompactTextString(m) }
func (*BaseInfo) ProtoMessage()    {}
func (*BaseInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_abe44bf90c1c2369, []int{0}
}

func (m *BaseInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseInfo.Unmarshal(m, b)
}
func (m *BaseInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseInfo.Marshal(b, m, deterministic)
}
func (m *BaseInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseInfo.Merge(m, src)
}
func (m *BaseInfo) XXX_Size() int {
	return xxx_messageInfo_BaseInfo.Size(m)
}
func (m *BaseInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BaseInfo proto.InternalMessageInfo

func (m *BaseInfo) GetBaseInfoTypeId() int32 {
	if m != nil {
		return m.BaseInfoTypeId
	}
	return 0
}

func (m *BaseInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BaseInfo) GetColumn() string {
	if m != nil {
		return m.Column
	}
	return ""
}

func (m *BaseInfo) GetSortNo() int32 {
	if m != nil {
		return m.SortNo
	}
	return 0
}

type Pair struct {
	Key                  int32    `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Values               string   `protobuf:"bytes,2,opt,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pair) Reset()         { *m = Pair{} }
func (m *Pair) String() string { return proto.CompactTextString(m) }
func (*Pair) ProtoMessage()    {}
func (*Pair) Descriptor() ([]byte, []int) {
	return fileDescriptor_abe44bf90c1c2369, []int{1}
}

func (m *Pair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pair.Unmarshal(m, b)
}
func (m *Pair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pair.Marshal(b, m, deterministic)
}
func (m *Pair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pair.Merge(m, src)
}
func (m *Pair) XXX_Size() int {
	return xxx_messageInfo_Pair.Size(m)
}
func (m *Pair) XXX_DiscardUnknown() {
	xxx_messageInfo_Pair.DiscardUnknown(m)
}

var xxx_messageInfo_Pair proto.InternalMessageInfo

func (m *Pair) GetKey() int32 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *Pair) GetValues() string {
	if m != nil {
		return m.Values
	}
	return ""
}

type SayResponse struct {
	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	// 数组
	Values []string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	// map
	Header               map[string]*Pair `protobuf:"bytes,3,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Type                 RespType         `protobuf:"varint,4,opt,name=type,proto3,enum=catalog.RespType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SayResponse) Reset()         { *m = SayResponse{} }
func (m *SayResponse) String() string { return proto.CompactTextString(m) }
func (*SayResponse) ProtoMessage()    {}
func (*SayResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_abe44bf90c1c2369, []int{2}
}

func (m *SayResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SayResponse.Unmarshal(m, b)
}
func (m *SayResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SayResponse.Marshal(b, m, deterministic)
}
func (m *SayResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SayResponse.Merge(m, src)
}
func (m *SayResponse) XXX_Size() int {
	return xxx_messageInfo_SayResponse.Size(m)
}
func (m *SayResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SayResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SayResponse proto.InternalMessageInfo

func (m *SayResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *SayResponse) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *SayResponse) GetHeader() map[string]*Pair {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *SayResponse) GetType() RespType {
	if m != nil {
		return m.Type
	}
	return RespType_NONE
}

func init() {
	proto.RegisterEnum("catalog.RespType", RespType_name, RespType_value)
	proto.RegisterType((*BaseInfo)(nil), "catalog.BaseInfo")
	proto.RegisterType((*Pair)(nil), "catalog.Pair")
	proto.RegisterType((*SayResponse)(nil), "catalog.SayResponse")
	proto.RegisterMapType((map[string]*Pair)(nil), "catalog.SayResponse.HeaderEntry")
}

func init() { proto.RegisterFile("p.proto", fileDescriptor_abe44bf90c1c2369) }

var fileDescriptor_abe44bf90c1c2369 = []byte{
	// 307 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0x5f, 0x4f, 0xb3, 0x30,
	0x18, 0xc5, 0xdf, 0x02, 0xe3, 0xcf, 0x43, 0xde, 0x05, 0x7b, 0x61, 0x88, 0x57, 0x04, 0xa3, 0x21,
	0x26, 0x12, 0x83, 0x37, 0x8b, 0x77, 0xea, 0x48, 0xb6, 0x1b, 0x34, 0x9d, 0x5f, 0xa0, 0xdb, 0xea,
	0x34, 0x02, 0x25, 0x94, 0x2d, 0xe1, 0xeb, 0xfa, 0x49, 0x4c, 0x4b, 0x9d, 0xe8, 0xdd, 0x39, 0x4f,
	0xfb, 0x3b, 0xf4, 0x3c, 0x80, 0xd3, 0xa4, 0x4d, 0xcb, 0x3b, 0x8e, 0x9d, 0x0d, 0xed, 0x68, 0xc9,
	0x77, 0xf1, 0x01, 0xdc, 0x07, 0x2a, 0xd8, 0xb2, 0x7e, 0xe5, 0xf8, 0x12, 0xa6, 0x6b, 0xad, 0x5f,
	0xfa, 0x86, 0x2d, 0xb7, 0x21, 0x8a, 0x50, 0x32, 0x21, 0x7f, 0xa6, 0x18, 0x83, 0x55, 0xd3, 0x8a,
	0x85, 0x46, 0x84, 0x12, 0x8f, 0x28, 0x8d, 0x4f, 0xc1, 0xde, 0xf0, 0x72, 0x5f, 0xd5, 0xa1, 0xa9,
	0xa6, 0xda, 0xc9, 0xb9, 0xe0, 0x6d, 0x57, 0xf0, 0xd0, 0x52, 0x59, 0xda, 0xc5, 0x37, 0x60, 0x3d,
	0xd3, 0xf7, 0x16, 0x07, 0x60, 0x7e, 0xb0, 0x5e, 0x7f, 0x48, 0x4a, 0x49, 0x1c, 0x68, 0xb9, 0x67,
	0x42, 0xe7, 0x6b, 0x17, 0x7f, 0x22, 0xf0, 0x57, 0xb4, 0x27, 0x4c, 0x34, 0xbc, 0x16, 0x4c, 0x92,
	0x95, 0xd8, 0x29, 0xd2, 0x23, 0x52, 0xfe, 0x22, 0xcd, 0x1f, 0x12, 0xcf, 0xc0, 0x7e, 0x63, 0x74,
	0xcb, 0xda, 0xd0, 0x8c, 0xcc, 0xc4, 0xcf, 0xa2, 0x54, 0xb7, 0x4f, 0x47, 0x79, 0xe9, 0x42, 0x5d,
	0xc9, 0xeb, 0xae, 0xed, 0x89, 0xbe, 0x8f, 0x2f, 0xc0, 0xea, 0xfa, 0x86, 0xa9, 0xb7, 0x4f, 0xb3,
	0x93, 0x23, 0x27, 0x21, 0xb9, 0x0c, 0xa2, 0x8e, 0xcf, 0x16, 0xe0, 0x8f, 0xe8, 0x71, 0x27, 0x6f,
	0xe8, 0x74, 0x0e, 0x13, 0xf5, 0x16, 0x55, 0xc9, 0xcf, 0xfe, 0x1f, 0x83, 0xe4, 0x0e, 0xc8, 0x70,
	0x76, 0x67, 0xcc, 0xd0, 0xd5, 0x35, 0xb8, 0xdf, 0xd9, 0xd8, 0x05, 0xab, 0x78, 0x2a, 0xf2, 0xe0,
	0x1f, 0x06, 0xb0, 0xef, 0x57, 0x8f, 0x79, 0x31, 0x0f, 0x10, 0xf6, 0xc1, 0x99, 0xe7, 0x83, 0x31,
	0xd6, 0xb6, 0xfa, 0x9b, 0xb7, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xfe, 0x12, 0xfd, 0x2d, 0xd8,
	0x01, 0x00, 0x00,
}
