###
http://scoring.appapi.lingcb.cn/coupon_item/Get?ItemId=1909121430210016
access-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJqdGkiOiIzZWMzYzczZC1mZjA4LTQwOTktODJkZS0xNmIxMWZkOTk3MTUiLCJjcGMiOiJxcTEiLCJlcWkiOiIiLCJzdWIiOiJxcTEwMSIsImV4cCI6MTU2ODczODE2Mi4wMTE0MjQ4LCJpYXQiOjE1Njg2NTE3NjIuMDExNDI0OH0.ODliNDNhOTU0YzBlNzI0YjkwOWFhNjBkNTk3MDQzODI3NWZmZGQxNDdlMzc4YWYzNjlkYmIzYjYzYTY0YTRjZGU5NjNkY2E0YWE1MzQ0OGQzZmQ5ZmNiYTU0ZmI0ODdmMzdiOWZjYmY5OTE0YzBmZDQ4Y2FkYzQ1ZGZkNGE1MTE

###
http://scoring.appapi.lingcb.cn/coupon_item/GetsByMember?MemberId=36c0ab1a-ca4b-11e9-a684-0e9c9907ed8c&Status=0&PageIndex=1&PageSize=4&CouponType=0
access-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJqdGkiOiIzZWMzYzczZC1mZjA4LTQwOTktODJkZS0xNmIxMWZkOTk3MTUiLCJjcGMiOiJxcTEiLCJlcWkiOiIiLCJzdWIiOiJxcTEwMSIsImV4cCI6MTU2ODczODE2Mi4wMTE0MjQ4LCJpYXQiOjE1Njg2NTE3NjIuMDExNDI0OH0.ODliNDNhOTU0YzBlNzI0YjkwOWFhNjBkNTk3MDQzODI3NWZmZGQxNDdlMzc4YWYzNjlkYmIzYjYzYTY0YTRjZGU5NjNkY2E0YWE1MzQ0OGQzZmQ5ZmNiYTU0ZmI0ODdmMzdiOWZjYmY5OTE0YzBmZDQ4Y2FkYzQ1ZGZkNGE1MTE
